### ISSUE TITLE
wipe out home menu by clicking save before load

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab-admin-console#125]
On "Content Menus" tab, I changed some menu properties, and clicked save.
This destroyed the menus on home page (menu.json was still intact, but menu_items_1 was an empty list []).

**Comment by tim-moody** [comment]
This is made more complicated by the fact that if you do a download of zims or oer2go items the stored menu item list will also be out of sync with the displayed/edited list. We can load the menu automatically, on startup, but it will be difficult to know when to load it during downloads.

Perhaps a timestamp should be added to menu.json.

**Comment by tim-moody** [comment]
warning added if save and menu added
