### ISSUE TITLE
zmq.so no longer exists, php ini needs to reflect tht

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab-admin-console#16]
On ubuntu, debugging nextcloud, php gets an error message about zmq.so no found. This was after running the console ./install. Deleting line 207 at https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/tasks/main.yml might be sufficient (I just deleted 20-zmq.ini to verify)

**Comment by tim-moody** [comment]
probably all the zmq.ini need to be removed

**Comment by tim-moody** [comment]
hopefully fixed in #17
