### ISSUE TITLE
Editing menu item from admin console breaks link from home page

### ISSUE THREAD

**Issue by mir123** [iiab/iiab-admin-console#163]
I edited the "credits" menu item from the admin console (to translate to Spanish), which broke the link from the home page. The link appeared as `http://box.lan/undefined`. Copying the link text (`commons/html/credits.html`) made that  `box.lan/undefined/commons/html/credits.html`. Reverting to the original version of en-credits.json fixed the issue.

Steps:

Click on Content menus/Edit menu items
Change text in item and description
Click Update Menu Item Definition

**Comment by mir123** [comment]
Content of `en-credits.json` after editing from admin console:

```
{
  "lang": "en", 
  "extra_description": "", 
  "description": "Gracias a todas las personas que colaboraron y curaron el contenido usado por Internet-in-a-Box.", 
  "title": "Cr\u00e9ditos", 
  "extra_html": "", 
  "change_ref": "admin_console - edit", 
  "footnote": "", 
  "start_url": "common/html/credits.html", 
  "change_date": "2019-04-18", 
  "logo_url": "credits.png", 
  "intended_use": "webroot"
}
```

**Comment by holta** [comment]
Thanks @mir123

@tim-moody was working on the Spanish credits right before he left last week.  He's travelling overseas now but will respond here soon in the coming week-or-so to help you and all of us get this right!

PS i'll publish a more clear community process for volunteers to offer translation & similar improvements to http://FAQ.IIAB.IO when the dust settles here in coming weeks.

**Comment by tim-moody** [comment]
please try your edit again but only edit the description as that has no unicode characters in it.
if that fails, please email me the json file.

**Comment by tim-moody** [comment]
There is at least one bug here and it is not unicode.
webroot menu-def type uses moddir (not starturl), but the moddir value is not written back to the json file on edit.

**Comment by tim-moody** [comment]
I am also puzzled that the title switches from "title": "Créditos" to "title": "Cr\u00e9ditos", though both seem to be rendered correctly in js-menu

**Comment by holta** [comment]
@tim-moody can this be closed now thanks to https://github.com/iiab/iiab-admin-console/pull/178 ?
