### ISSUE TITLE
js menu fails to start due to missing /common/assets/osm_version_idx.json

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#168]
/common/assets/osm_version_idx.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)

after install of iiab and iiab-admin-console

**Comment by georgejhunt** [comment]
I wonder if this failure is an upgrade.
I found that I needed to do git pull master on both iiab and console, and
then at a minimum ./runrole osm-vector on iiab and ./install on the console.

**Comment by tim-moody** [comment]
I did the upgrades, but not the runrole.

Don't think the menu should fail if you aren't using maps

**Comment by georgejhunt** [comment]
Yes I discovered that it failed without iiab, and have a fix that I
have not tested yet.

**Comment by tim-moody** [comment]
no longer seen
