### ISSUE TITLE
Overwrite of menu-defs

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#175]
Has anyone seen that doing a repeat of install for Admin Console overwrites modified menu-defs. This was supposed to have been prevented some time ago.

**Comment by tim-moody** [comment]
I just observed it.

**Comment by georgejhunt** [comment]
Maybe I don't understand the question. But it looks to me that line 26
in cp-menus would do that.

"rsync -av roles/js-menu/files/menu-files $MENUDIR"

**Comment by tim-moody** [comment]
fixed
