### ISSUE TITLE
xo-services vs xo_services

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab-admin-console#20]
We must have moved incompletely from xo-services to xo_services. There are still a few tags in iiab that are xo-services. But all the variables are xo_services. 

But /etc/iiab/config_vars.yml still has xo-services, and therefore does not have any effect.

**Comment by tim-moody** [comment]
5-xo-services is the name of the role, so why was the flag changed to xo_services? Looks to be recent as most are in os_localvars. There are many xo-services references in iiab.

our pattern used to be hyphen in names and underscore before install or enabled.

**Comment by tim-moody** [comment]
change to xo_services has been made
