### ISSUE TITLE
OSM variable missing?

### ISSUE THREAD

**Issue by KW4NP** [iiab/iiab-admin-console#200]
I can't seem to finish installing the admin console since the latest update.  It seems like there is a variable missing but I'm not sure where it's supposed to be.  Have you seen this before?

```
TASK [js-menu : Put the OSM update program in place] ********************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'vector_map_path' is undefined"}
	to retry, use: --limit @/opt/iiab/iiab-admin-console/iiab-admin.retry
```

**Comment by holta** [comment]
@KW4NP when is the last time you ran...?
```
cd /opt/iiab/iiab
git pull
```
Just to be sure, have you tried that, to make sure your /opt/iiab/iiab/vars/default_vars.yml is up-to-date?

SEPARATELY: in the above directory, you might also run `iiab-install --reinstall` ?

**Comment by KW4NP** [comment]
That fixed it, thanks.
