### ISSUE TITLE
Raspberry Pi User Guide (PDF)

### ISSUE THREAD

**Issue by randytate** [iiab/iiab-admin-console#217]
Downloaded a RPi guide from [here](https://www.raspberrypi.org/magpi-issues/Beginners_Guide_v1.pdf) as `/library/www/html/modules/en-rpi_guide/Raspberry_Pi_Beginners_Guide_v1.pdf`.

Then updated `/library/www/html/js-menu/menu-files/menu-defs/en-rpi_guide.json` as attached ...
[en-rpi_guide.json.zip](https://github.com/iiab/iiab-admin-console/files/3317246/en-rpi_guide.json.zip)

(For KoC/Uganda; as requested by @holta)

**Comment by holta** [comment]
@tim-moody you mentioned you blocked http://oer2go.org/viewmod/en-rpi_guide as it had troubles &mdash; if you want to unblock it, here are all the materials for you to restore this as provided by @randytate ?

I would not know how to proceed.

**Comment by tim-moody** [comment]
OK. I didn't understand you were asking me to update the RACHEL module. Not sure I can do that.

**Comment by tim-moody** [comment]
so I just allowed the rpi guide back in, but the one rachel has is user guide at 154 pp and Randy's is beginner at 244 pp

**Comment by tim-moody** [comment]
from 2014

**Comment by holta** [comment]
Both from 2014?

**Comment by tim-moody** [comment]
Randy's is from 2018.

There are two choices:

1) Try to get rachel to use the later pdf
2) Create and host our own module with it.

I lean towards the latter.

**Comment by tim-moody** [comment]
Actually, do we have rights to https://www.raspberrypi.org/magpi/issues/beginners-guide/

**Comment by holta** [comment]
Ideally, can we use both from 2018?

**Comment by tim-moody** [comment]
You can use anything you can find.

**Comment by tim-moody** [comment]
done
