### ISSUE TITLE
en-coreknowledge.json has syntax error

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#220]
probably the continuation \ breaks json parsing

**Comment by tim-moody** [comment]
also, no point in having all these extra, unused fields from the catalog

**Comment by holta** [comment]
> also, no point in having all these extra, unused fields from the catalog

Agreed.  What script is generating all these useless fields (from OER2Go site's metadata or some catalog presumably? )

And which fields should be removed vs. kept when we hopefully find someone to fix this properly?
