### ISSUE TITLE
Admin Console reports osm region as installed when it isn't

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#229]
after selecting en-osm-omt_middle_east_2017-07-03_v0.23/en-osm-omt_middle_east_2017-07-03_v0.23.zip I selected South America and got alert that already installed.

**Comment by georgejhunt** [comment]
I think this points to a bug. My code does not silently ignore checkboxes that are already installed -- and the alert probably does not display which region is already installed -- leading to confusion.

**Comment by tim-moody** [comment]
Not sure what to say. The previous version did not have this problem. Multiple regions could be installed at once. Those already installed were silently skipped. This version can install one region at a time, but any installed region will mark all as installed.

We plan to rewrite this later as the data and ui both have planned revisions.

My vote is to go back to what we had before.

**Comment by georgejhunt** [comment]
I agree

**Comment by georgejhunt** [comment]
Or we could include in the alert the identity of the region is already
installed. I think that if one region is installed, and there are two check
boxes, the logic will flag the one that is already installed, and silently
go to work to install the second one.

**Comment by tim-moody** [comment]
it won't. it will mark both as installed

**Comment by georgejhunt** [comment]
But if we changed line 304 from "break" to "continue" ,  and deleted the
alert for already installed, I would work, and not pester the user about
what was already installed.

**Comment by tim-moody** [comment]
Just so I'm clear, will the functionality be different in any way from what was there before?

**Comment by georgejhunt** [comment]
Give me some time to set up a test case. I've been wrong too many times.

**Comment by georgejhunt** [comment]
I suggest that we comment out the alert at 309 in admin-console.js. (PR 232
does this) ie: alert ("Selected Map Region is already installed.\n");
I've tested this fix.
It installs a second region, after a first one has already been installed
on an earlier click on the "install selected regions" button.  It silently
refuses to attempt a second install of a region that is already installed
(no change from previous behavior).

I fudged the version of regions.json in
/library/www/osm-vector-maps/maplist/assets to request an earlier version
of a package that was already installed, and it downgraded properly.

**Comment by georgejhunt** [comment]
addendum to the report. I forgot to reboot the test machine, before
downloading a downgraded map region.
The front end thought it was downloading one thing, the backend downloaded
the same (unchanged) one again (the communication is via region name (via
the url associated with that region in regions.json, and the back end will
only pick up a changed regions.json at startup.

Probably more of a problem for testers, than it is for our installed base.

**Comment by tim-moody** [comment]
I have not yet heard any reason not to go back to what was there before.

**Comment by georgejhunt** [comment]
The one before refused to install a new release of a region that was
already installed -- without hand editing of
../common/assets/vector-maps-idx.json.

**Comment by holta** [comment]
@georgejhunt is this still an issue?

(Or can I close parent ticket iiab/iiab#1793 now?)

**Comment by holta** [comment]
@georgejhunt suggests we close this and parent tkt iiab/iiab#1793:

https://github.com/iiab/iiab/issues/1793#issuecomment-570746434
