### ISSUE TITLE
iiab_update_menus uses wrong language code

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#238]
e.g. sp for es

**Comment by holta** [comment]
Largely resolved by #229

See iiab/iiab#1870 and @tim-moody's suggestion that a rewrite of rewrite [iiab-make-kiwix-lib.py](https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/iiab-make-kiwix-lib.py) & [iiab_update_menus.py](https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/templates/scripts/iiab_update_menus.py) would be best.
