### ISSUE TITLE
authenticate on both sudo and iiab-admin groups

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#345]
- iiab_admin_user should also probably be in iiab-admin group and not sudo
- could be created in iiab-admin-console
- iiab_admin_user could also not have a login

**Comment by tim-moody** [comment]
iiab_admin_user  could also not have a login

for iiab after this is implemented:
- name: Create a iiab-admin group
  group:
    name: iiab-admin
    state: present

- name: Create user {{ iiab_admin_user }} in group iiab-admin for Admin Console; set password from iiab_admin_pwd_hash if newly creating account
  user:
    name: "{{ iiab_admin_user }}"
    name: "{{ iiab_admin_user }}"    # iiab-admin
    password: "{{ iiab_admin_pwd_hash }}"
    update_password: on_create
    shell: /bin/bash
    groups: iiab-admin

**Comment by holta** [comment]
See merged PR iiab/iiab-admin-console#346

**Comment by tim-moody** [comment]
implemented in #348
