### ISSUE TITLE
Undeclared python3-requests dependency

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab-admin-console#354]
https://gist.github.com/sptankard/1dbe2957abd14b2cd96f783235dbc136 mentions  python3-requests having to be installed by hand, 
https://github.com/iiab/iiab-factory/issues/154 contains further discussion and mentions duplicate imports.

**Comment by tim-moody** [comment]
will be fixed in next release cycle

**Comment by tim-moody** [comment]
fixed
