### ISSUE TITLE
0.5.1 bugs

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#356]
- [x] going from regions to addons does not refresh space estimate; user can click refresh display
- [x] addons does not warn if base satellite not installed; should satellite base be required?
- [x] forgot to add new menu def to repo and to home
- [x] cmdsrv fails to start if osm vect maps not enabled (adm-map-catalog.json not installed)
- [x] had no map display for regions (again because enabled is false)

**Comment by holta** [comment]
Close this, if ticket is complete?
