### ISSUE TITLE
clone menu def allows name with only lang code

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#370]
name field can be blanked and selecting language puts xx- but nothing more. this can be saved and uploaded.

**Comment by tim-moody** [comment]
it even save .json (no name)

**Comment by holta** [comment]
Example:

https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-.json

**Comment by tim-moody** [comment]
suffix is also not used

**Comment by tim-moody** [comment]
#371 fixes
