### ISSUE TITLE
iiab zim library missing fields

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#373]
https://ftp.nluug.nl/pub/kiwix/library/library_zim.xml has the following fields not in iiab's library.xml for iiab produced zims for example:

name="wikipedia_es_climate_change"  
flavour="_maxi" 
url="http://download.kiwix.org/zim/wikipedia/wikipedia_es_climate_change_maxi_2020-10.zim.meta4" 

OR
name="wikipedia_en_all" 
flavour="_mini"

name is similar to our perma-ref, but at a more general level in that included content (maxi, etc) is broken out separately

**Comment by tim-moody** [comment]
Proposed utilities:

mk-zim-cat-item (zim file name, download source)
- write temp library.xml with only this zim
- read xml to dict
- compute name and flavour from file name
- compute url from download source and file name
- add name, flavour, url properties
- write to  zim file name.json and store in repo

mk-iiab-zim-cat
- for each zim file name.json
  - read json
  - append item and properties to list
- write list to iiab-zim-catalog.json in repo

**Comment by georgejhunt** [comment]
If I understand correctly, we will have our own zim catalog in json format
in our repo, and concatenate kiwix's xml (no transformation required) with
our transformed json->xml (generated on the fly every time we download a
new version of kiwix catalog).

**Comment by tim-moody** [comment]
Not quite. Our current kiwix catalog is /etc/iiab/kiwix_catalog.json, so
already transformed to json for use by admin console. We will merge our
catalog, already in json, with that.

/library/zims/library.xml is not a catalog per se but records what is
installed.

**Comment by tim-moody** [comment]
utilities have been implemented
