### ISSUE TITLE
error when maps not installed

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#409]
map_functions.js 287 undefined property enabled when osm not installed

**Comment by tim-moody** [comment]
could use ansibleRolesStatus, but currently only read for presets

**Comment by tim-moody** [comment]
ini read in init
getXsceIni () could be renamed as well

**Comment by holta** [comment]
Extremely valuable work, to sanitize our dependencies, thank you @tim-moody

Reminiscent of PR #390 which improves the situation for Kiwix.

**Comment by holta** [comment]
Is PR #412 good enough to close this?  Or is further work forthcoming?
