### ISSUE TITLE
Cannot change server's network role?

### ISSUE THREAD

**Issue by sjml** [iiab/iiab-admin-console#474]
I may be misunderstanding how this panel in the admin console works... from what I can tell in the code, the network role gets set by analyzing what is available on different interfaces, not from the console? 

I currently have a Raspberry Pi 4 with its access point disabled and connected to the internet via its ethernet port. But it always comes up in "Gateway" mode instead of "Appliance." I've tried changing the radio button, saving the configuration, and doing "Install Configured Options" but every time I reboot it still comes up as "Gateway." Is there some other way I need to be changing this option? 

It's probably not horrible to be set as a Gateway in this instance, but I'm trying to see if I can just have it sit on the network as its own machine without caring about a broader role. 

Thanks for whatever help you can offer.

**Comment by holta** [comment]
@sjml can you please run `sudo iiab-diagnostics` and post the resulting *sprunge.us* URL here?

Thank You!

**Comment by sjml** [comment]
Thanks for your quick response! [The diagnostics are up here](http://sprunge.us/Z7k2MP). I'm sure this is just something I'm misunderstanding, but appreciate you taking a look.

**Comment by tim-moody** [comment]
As IIAB is installed various configuration values are written to /etc/iiab/iiab.ini, one of which is [computed_network]-> iiab_network_mode. This is then assigned to network mode in Admin Console. So the question is why does yours say Gateway, whereas the one I am looking at says Appliance. Mine is a VM.

**Comment by tim-moody** [comment]
The other comment to make is that the radio buttons in Admin Console represent the user's wishes, but they may not be possible. The network functions try to implement those wishes and they fall back to what is deemed possible. For some reason those functions seem to think Gateway describes your configuration.

**Comment by sjml** [comment]
Is there a way to debug the process of computing the network? Do I need to disable the WiFi entirely, rather than just turning off the AP?

**Comment by tim-moody** [comment]
Look at /opt/iiab/iiab/iiab-network.log. Add 'computed_network' variable values to /etc/iiab/iiab.ini

You can narrow the search by running iiab-network in /opt/iiab/iiab after any changes

**Comment by tim-moody** [comment]
Think you are right. Must be quite an old regression. Possibly home_url as well.

**Comment by holta** [comment]
Thanks so much @sjml for helping us work through this.
Hopefully this can be made understandable for everyone, and you can help us verify shortly.

Aside: Are you in Lebanon?

**Comment by jvonau** [comment]
> Is there a way to debug the process of computing the network? Do I need to disable the WiFi entirely, rather than just turning off the AP?

What is a bit confusing is the 'LAN' device (br0) can also used with network bluetooth devices not just hostapd using the WiFi chipset and is left active for that reason unless overridden. A 'gateway' in the truest sense should provide internet access but that is an option controlled by the user, the device layout naming was not changed it is just a representation of the maximum of what could be enabled. In the end what do you want to achieve? I'll wait for a response, your option many not currently be available via the admin-console but is available in the underling network code and possible with entries in local_vars.yml.

**Comment by sjml** [comment]
> Think you are right. Must be quite an old regression. Possibly home_url as well.

OK, so just so I'm clear -- sounds like this is a bug, and not something I messed up with my particular setup? (As I said in the original post, this is not blocking me from anything, just want it to be set right as much as possible.)

> Aside: Are you in Lebanon?

Yup! The IIAB units I'm building will go to Iraq, though. (I work in multiple sites around the region.)

**Comment by tim-moody** [comment]
http://iiab.me/beqaa/ was built quite some time ago, but may be of interest.

**Comment by sjml** [comment]
> 



> http://iiab.me/beqaa/ was built quite some time ago, but may be of interest.

Oh wow -- do you know where in the Beqaa this was/is deployed? Looks like a great set of packages for rural Lebanon.

**Comment by tim-moody** [comment]
$('#'+ this.name).is(":visible") returns false for fields that are not hidden

**Comment by holta** [comment]
> $('#'+ this.name).is(":visible")

Is this an issue with `function setConfigVars ()` in... ?

https://github.com/iiab/iiab-admin-console/blob/bd44a86fb723edc6de421ead0ae62898efc42c81/roles/console/files/js/admin_console.js#L1081

**Comment by tim-moody** [comment]
I am in the process of modifying all this to allow installation of roles from adm cons. I would prefer not to fix it here. As @jvonau mentioned the workaround is to set a missing variable in /etc/iiab/local_vars.yml and then run ansible.

**Comment by tim-moody** [comment]
closing. please reopen if problem persists.
