### ISSUE TITLE
ol.js & olms.js looking for a .map file?

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab-admin-console#485]
>Source map error: Error: request failed with status 404
Resource URL: http://192.168.122.35/common/js/ol.js
Source Map URL: ol.js.map
Source map error: Error: request failed with status 404
Resource URL: http://192.168.122.35/common/js/olms.js
Source Map URL: olms.js.map
![Screenshot from 2022-05-01 23-50-35](https://user-images.githubusercontent.com/5579710/166185841-e44039ee-8cda-488c-8cd9-2431f47e0b99.png)
https://github.com/iiab/iiab-admin-console/blob/master/roles/console/files/index.html#L447-L448
https://github.com/iiab/iiab/commit/1bdef1d6d34ae17e927236f7b1cf181a9685c3bd
https://github.com/iiab/iiab/commit/a8b04717218ce796ced2fdf63d6318c945cf38c1

**Comment by tim-moody** [comment]
browsers, chrome and likely others, look for a .map file in their javascript console to help debug minified js files. they are not used by the application itself.
