### ISSUE TITLE
need way to force menu json refresh when modules are added

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#493]
A user downloads a module with Admin Console. Corresponding menu def is added to menu.json, but does not display.

**Comment by tim-moody** [comment]
test with `mount |grep portal`
expectation is that if /root/.cache/doc is in list the df will show error

**Comment by tim-moody** [comment]
could try substituting fetch for $.getJSON setting cache to no-cache
https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by tim-moody** [comment]
#494 to testing

**Comment by jvonau** [comment]
> could try substituting fetch for $.getJSON setting cache to no-cache

That's a good idea as menu.json can change before the entire cache expires, if it expires at all.

**Comment by tim-moody** [comment]
>https://github.com/iiab/iiab/issues/3231

why clutter this with irrelevant other issues?
