### ISSUE TITLE
6.4 backward compatibility

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#51]
iiab 6.5 changes ini variable section from network to computed_network

/opt/admin/console/js/admin_console.js follows this change and is incompatible with earlier versions
which require line 622 setRadioButton("gui_desired_network_role", iiab_ini.network.iiab_network_mode)

**Comment by tim-moody** [comment]
This is now resolved, but with conditional logic that adds complexity and should not have been required. We should have reverted the name change in iiab.

**Comment by holta** [comment]
Ref #63 "more accommodate rename of variable in iiab"
