### ISSUE TITLE
Feature Request: remove menu item from menu when content deleted

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#510]
iiab/iiab#3375

**Comment by tim-moody** [comment]
- for zims and modules
- loop through menu and find any item with same target and remove
- need to refresh menu in adm cons

**Comment by holta** [comment]
1) "Hoarders" who cram in "everything" not only represent human nature &mdash; but in fact this remains the very best way to measure drive space for now &mdash; i.e. max'ing out your drive and then taking a few step back from the Cliff's Edge (e.g. freeing up ~10%-or-whatever of the drive space!)

2) Removing Map Packs is too complex at this time, I definitely agree :sweat_smile:

**Comment by holta** [comment]
This kind of _"librarians need to weed out"_ UX is inherently hard as hell.  But clearly deletion UI/affordances are needed!  On a closely related note:

1) "Hoarders" who cram in "Everything" not only represent human nature &mdash; but in fact this remains the very best way to measure drive space for now &mdash; i.e. max'ing out your drive and then taking a few step back from the Cliff's Edge (e.g. later on freeing up ~10%-or-whatever of the drive space, to create necessary Breathing Room, by deleting a few Content Packs etc!)

2) Removing Map Packs is too complex at this time, I definitely agree :sweat_smile:

**Comment by tim-moody** [comment]
#513
