### ISSUE TITLE
es-blockly-games wrong url

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#521]
in oer2go catalog url is es-blockly-games but should be es-blockly_games

**Comment by tim-moody** [comment]
It is correct here https://github.com/iiab/iiab-admin-console/commit/949b83405ad10b68c0448f29b5bba3714ca08bce

**Comment by tim-moody** [comment]
actaully both are in the catalog

https://github.com/iiab/iiab-admin-console/blob/3ed44b581b1b65cad44ae60c217e4e653c10b286/roles/cmdsrv/files/json/oer2go_catalog.json

for the es-blockly_games the description is
"delete me someday - this module has been superceded, but is here for people still updating against the old module (after they do, they'll automatically get the new one next time)",

**Comment by tim-moody** [comment]
Admin console shows both

**Comment by tim-moody** [comment]
looks like leaving the module name as es-blockly-games and changing the rsync url works.

**Comment by holta** [comment]
ASIDE: OER2Go (https://rachel.worldpossible.org/content) appears to have fallen far out of date.

These more recent ZIP files (published by Google itself) are much more comprehensive, and bonus in 56 different languages:

https://github.com/google/blockly-games/wiki/Offline

**Comment by tim-moody** [comment]
>looks like leaving the module name as es-blockly-games and changing the rsync url works.

no. failed. get confusion when the working dir is created

**Comment by randytate** [comment]
I tried changing rsync urls in various config files, but it never worked.  Ultimately, I rsync'ed it manually, then ran the install script.  That worked, but I ended up with the "delete me someday" menu.  Then I found the corresponding menu definition file and edited it to say "Blockly Games".

**Comment by tim-moody** [comment]
to use https://github.com/google/blockly-games/wiki/Offline with es for example
download https://github.com/google/blockly-games/raw/offline/generated/blockly-games-es.zip
unzip
rename blockly-games/es-blockly-games and put in modules

but we need a catalog and we don't use wget and uzip, but rather rsync.

**Comment by holta** [comment]
> https://github.com/google/blockly-games/wiki/Offline with es for example
> download https://github.com/google/blockly-games/raw/offline/generated/blockly-games-es.zip
> unzip
> rename blockly-games/es-blockly-games and put in modules

Yes!

And as hairy as this appears &mdash; one of us should definitely consider automating the intall path for this extremely popular "4MB" Content Pack in 2023.

Even if IIAB cannot support all 56 languages possibly.

**Comment by tim-moody** [comment]
deploy es-blocky-games on iiab rsync host and point url to in in catalog

**Comment by tim-moody** [comment]
good enough
