### ISSUE TITLE
adm cons install fails after #526

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#529]
TASK [cmdsrv : Install speedtest-cli into virtual environment] ************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python3", "-m", "venv", "/usr/local/speedtest", "/usr/local/speedtest"], "msg": "stdout: The virtual environment was not created successfully because ensurepip is not\navailable.  On Debian/Ubuntu systems, you need to install the python3-venv\npackage using the following command.\n\n    apt install python3.10-venv\n\nYou may need to use sudo with that command.  After installing the python3-venv\npackage, recreate your virtual environment.\n\nFailing command: ['/usr/local/speedtest/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']\n\n"}

**Comment by holta** [comment]
Smoke testing on RasPiOS and 20.04 wasn't quite enough, oh dear.

Hopefully @jvonau (or anybody) can identify a clean fix.

**Comment by holta** [comment]
Maybe Admin Console should also mandate `python3-venv` just like scripts/ansible now mandates.

Anyway that wouldn't hurt (for any/all components to declare their own dependencies, as much as is pragmatic anyway).

**Comment by holta** [comment]
My running assumption (@tim-moody can clarify) is that the above Ubuntu 22.04 test/fail took place with an older install of iiab/iiab...

**Comment by tim-moody** [comment]
correct me if I am wrong, but python3-venv is a dependency of ansible, not adm cons

Install was on vm after apt update upgrade and first install of newly pulled iiab and iiab-admin-console

**Comment by holta** [comment]
iiab/iiab now requires the install of `python3-venv`

iiab/iiab-admin-console apparently too, and probably make this preteq explicit?

**Comment by tim-moody** [comment]
>iiab/iiab now requires the install of python3-venv

so was it installed?

should adm cons install ansible?

**Comment by tim-moody** [comment]
anyway it was installed

root@iiab-kolibri:~# apt list |grep python3-venv

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-venv/jammy-updates 3.10.6-1~22.04 amd64

**Comment by holta** [comment]
On a fresh install on Ubuntu 22.04 this won't flare up right?

If that correct, I guess it's just a matter of hygiene preferences, i.e. if Admin Console should also mandate `python3-venv`.

**Comment by tim-moody** [comment]
OK. I reran the ansible script and now the install succeeded.

**Comment by tim-moody** [comment]
right you are
