### ISSUE TITLE
Add option to change hotspot password

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#546]
- Add option to Control panel, only RPI supported
- prompts for hotspot secured (default is checked) and hotspot password (default from hostapd_password)
- button to Change Hotspot Security
- calls CMDSRV with verb CTL-HOTSPOT
- updates local vars with hostapd_secure and hostapd_password
- puts values in hostapd.conf
- restarts hostapd

**Comment by holta** [comment]
Sounds great, per @nzola's request.

> Add option to Control panel, only RPI supported

Note that some people really do run IIAB on old refurb'd typically older laptops with internal WiFi hotspots, as explained here:

https://wiki.iiab.io/go/FAQ#Can_I_create_a_Wi-Fi_hotspot_using_an_old_laptop%3F

(So the functionality should really be work identically there, just like with Raspberry Pi, generally with the OS being Ubuntu or Mint or Debian.)

**Comment by holta** [comment]
Aside / hopefully it's completely extraneous and irrelevant (to @nzola's request here!) that `dhcpcd` is being replaced by `NetworkManager` on Raspberry Pi OS Bookworm — Raspberry Pi OS just revised their documentation on "Setting up a Wireless Access Point" here:

- https://github.com/raspberrypi/documentation/issues/2314#issuecomment-1525369999

PS This new OS will have many revisions when apparently arriving imminently in coming weeks, with testing looking solid so far, thanks to @EMG70:

- iiab/iiab#3526

**Comment by tim-moody** [comment]
Then I would say all bets are off.

**Comment by holta** [comment]
FYI the `dhcpcd` to `NetworkManager` change might not be as consequential or fearsome as it sounds.

e.g. if hostapd is still handling the internal hotspot in the end, and it generally all works, as several have in fact suggested (but I have not verified myself!)

**Comment by tim-moody** [comment]
First of all and after looking into implementing this, I would like to add the security flag and password to the existing Config Internal Wi-Fi Access Point panel. So you will first have to turn on password security and run ICO. This way I am not rewriting existing network functionality. Then if it is turned on you will be able to change the password under Control.

**Comment by holta** [comment]
Is the conclusion that enabling a hotspot password might take 2-4 minutes — i.e. if the hotspot does not already have a password?

Whereas subsequent changing of the password should be very fast?

**Comment by tim-moody** [comment]
yes

**Comment by nzola** [comment]
> yes. took 2 min 40s on my rpi 4 to go from unsecure enabled to secure enabled.

Great News! Thanks @tim-moody

**Comment by holta** [comment]
Should now be implemented by @tim-moody's:

- PR #548

@nzola let us know how this works for you?

**Comment by holta** [comment]
> @nzola let us know how this works for you?

"Your IIAB's internal Wi-Fi hotspot password is now rapidly changeable." is now posted to...

https://github.com/iiab/iiab/wiki/IIAB-8.1-Release-Notes#whats-new

**Comment by holta** [comment]
@nzola see also @tim-moody's new PR — regarding variable `wifi_up_down` — that toggles between dual-purpose internal WiFi and single-purpose internal WiFi:

- PR #551

Can you help us test this out?

**Comment by nzola** [comment]
Yes. I will test it when I return home tonight.

**Comment by holta** [comment]
> Yes. I will test it when I return home tonight.

@nzola is it ok to close this ticket?

**Comment by nzola** [comment]
@holta please don't close yet. I will run fresh IIAB  installs this week. If all is ok, I will let you know to close it. So far, i have not run any new install yet, but upgrade only.

**Comment by nzola** [comment]
> > Yes. I will test it when I return home tonight.
> 
> @nzola is it ok to close this ticket?

@holta Tested with fresh IIAB install ok. Please close this issue.
@tim-moody Thank you so much for your help!
