### ISSUE TITLE
Admin Console erroneously truncating ZIM filenames that contain dots

### ISSUE THREAD

**Issue by holta** [iiab/iiab-admin-console#69]
http://box/admin -> Utilties -> Display Job Status -> "Command" Column shows:

> /usr/bin/wget -c --progress=dot:giga http://download.kiwix.org/zim/stack_exchange/es.stackoverflow.com_es_all_2018-03.zim -O /library/working/zims/es.zim

The result is that ZIM files containing periods (.) are erroneously truncated.

In the case of **es.stackoverflow.com_es_all_2018-03.zim** above, the ZIM file's content was downloaded correctly, but it ended up misnamed as follows:

> root@box:/library/zims/content# ls -lh es.zim
-rw-r--r-- 1 root root 1.1G Mar 24 07:14 es.zim

**Comment by tim-moody** [comment]
fixed in #70
