### ISSUE TITLE
Mapping required from downloaded identity to menuItem.

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab-admin-console#96]

**Comment by georgejhunt** [comment]
Tim's problem statement:
2. There needs to be a function and supporting data that accepts a content reference (and probably content type) and returns the name of a menu-def. This would be used to make this match in the admin console and update the list of items that constitute a given menu, so not used at menuing runtime. Basically this is a cross reference to all of the menu-defs, for example passing intended_use = "zim  and zim =  " wikipedia_en_medicine_novid_2018-10.zim" would return en-wikipedia_en_medicine_novid or  intended_use = "html" and moddir = "en-medline_plus" would return  en-medline_plus. (These are the two easiest cases.)  Note that there is already a cross reference to relate the generic zim name, like wikipedia_en_medicine_novid, to the actually installed zim, like wikipedia_en_medicine_novid_2018-10.zim. These could be done whenever a new zim or oer2go module is added to the system. For other services like kalite, nextcloud, etc. there needs to be a means of determining if they are installed and enabled and adding the appropriate menu-def to the menu, probably this could be done at install time. There are also some stock items like credits, which should really be localized based on menu_lang in menu.json. (I am increasingly wishing I had chosen a different name for menu-def, but there are a lot of places to change this to menu-item, for example. Maybe for the next version.)

**Comment by georgejhunt** [comment]
It looks like the link between the downloaded filename to the menu item is as follows:
1. The file ./common/assets/zim-versions-idx.json provides a link from kixix-catalog:perma_ref to installed version file name(which includes a date).
2. The perma_ref item in the kiwix-catalog is equivalent with the "zim_name" item in the ./menu-files/menu-defs/* file tree.

The mapping to menuItems is yet to be explored for oer2go, and perhaps others.

**Comment by georgejhunt** [comment]
1. The zim_version_idx.json data is loaded at liine 133, and written as json at line 101, of iiab-make-kiwix-lib.py at the end of main().
2. The location of the menu.json file may be influenced by future soft coding in ansible, and may also be impacted by the folder location of the initial index.html (iiab.me creates multiple sites by locating the 2 files -- index.html and menu.json -- in folders other than home.
3. The desired end result is that a newly downloaded zim becomes visible in the menu automatically.
4. If there is more than one site, (think iiab.me), which menu.json to update?  Maybe the default is home/, and it is just always added there, if it does not already exist there.

**Comment by tim-moody** [comment]
4. I think we should only do /home. but perhaps we need an autoupdate_menu: True/False in case someone doesn't want the update behavior at all.

There are a few more wrinkles:

a) there could be more than one menu def that applies
b) the there could be no existing menu def that applies and we should create a stub for one.
c) if someone decides to remove an item from the menu we risk always putting it back. I played with having the menu list array hold a list of objects with each marked true or false so that we don't lose the info that the user does not want a given item even thought it has been downloaded. Or we just force them to remove it if it is not wanted.
d) we need to preserve the order prior to adding to the end of the list
e) I think it makes sense to have credits always last, so we may need to add an item as second to last.

In theory the menu-def for a give module is the directory name unless someone creates a second def to override something.

**Comment by georgejhunt** [comment]
I abandoned the database approach. I like the idea of capturing the mediaCount, articleCount,and size in zim_versions_idx, because the kiwix-catalog might change, and no longer have the data that goes with what was downloaded. But in testing, I find that your 4.b case is very likely. There are over 2200 entries in kiwix-catalog, 107 menu-defs that have a zim_filename item, and about 25 of them no longer match any perma_ref in kiwix-catalog.
My plan is to create a stub, as you suggested. Is there a default logo?

The consumer for zim_version_idx seems to be ./js/js-menu.hs lines 106-111
```// get name to instance index for zim files
var getZimVersions = $.getJSON(zimVersionIdx)
.done(function( data ) {
   //consoleLog(data);
zimVersions = data;})
.fail(jsonErrhandler);
```
I'm not yet  proficient in jquery. I think the change involves data.each(. But if you can suggest how to create the zimVersions object, it would help. 

The newly created zim_version_idx looks like this:
```{
  "wikem_en_all_novid": {
    "menuItem": "", 
    "mediaCount": "1070", 
    "zimFileName": "wikem_en_all_novid_2018-10", 
    "size": "38185", 
    "articleCount": "3434"
  }, 
  "wikibooks_en_all_nopic": {
    "menuItem": "", 
    "mediaCount": "44", 
    "zimFileName": "wikibooks_en_all_nopic_2017-07", 
    "size": "202025", 
    "articleCount": "77400"
  }, 
  "tes": {
    "menuItem": "en-test_zim", 
    "mediaCount": 0, 
    "zimFileName": "test", 
    "size": 0, 
    "articleCount": 0
  }, 
  "wikipedia_en_chemistry_novid": {
    "menuItem": "", 
    "mediaCount": "40425", 
    "zimFileName": "wikipedia_en_chemistry_novid_2018-10", 
    "size": "548433", 
    "articleCount": "20196"
  }, 
  "wikipedia_en_for-schools": {
    "menuItem": "en-wikipedia_en_for_schools", 
    "mediaCount": "125775", 
    "zimFileName": "wikipedia_en_for-schools_2018-09", 
    "size": "2435800", 
    "articleCount": "59466"
  }
```
I think we will need to move the zim info (size,mediaCount,articleCount) to json keyed by menuItem for the runtime substitution. Do you agree? We'll also need to add the oer2go  information into this new lookup object.

**Comment by tim-moody** [comment]
I think the ajax code above will not need changing to load this json into an object, but the object will be different and require changes to 

function calcZimLink(module){
	// if kiwix_url is defined use it otherwise use port
	var href = '';
	if(typeof zimVersions[module.zim_name] != 'undefined'){
	  href =  zimVersions[module.zim_name] + '/';
  	if ( menuConfig.hasOwnProperty('kiwixUrl'))
      href = menuConfig.kiwixUrl + href;
    else
      href = host + ':' + menuConfig.kiwixPort + '/' + href;
    }
  else
	  href = undefinedPageUrl + '?menu_item=' + module.menu_item_name + '&zim_name=' + module.zim_name; //not defined in zimVersions
	var html = calcItemHtml(href,module);
	return html
}

**Comment by tim-moody** [comment]
href = zimVersions[module.zim_name].zimFileName (etc.) should work

**Comment by georgejhunt** [comment]
Looking toward oer2go:

1. What is our strategy regarding update of menu.json? I'm inclined to add to menu-defs stubs, and change menu.json, if autoupdate_menu is not false. Shall the cmdsrv/files/scripts/oer2go_install_move.sh include a call to an 'update menu.js' function? -- Or where to put it? Maybe the menuItem-def requires a new value -- autogenerated: T/F
2. Do you agree that there will be a menu_info.json indexed by menuItem, holding all the substitution info for ##ARTICLES##, etc?
3. IIAB roles should contribute to menu.json -- maybe at install time for iiab-admin-console
4. Lots of zim file names differ in "nopic", "all","novid", and the presence of a logo in any could propagate into new stub menudefs.

**Comment by tim-moody** [comment]
1. and 2. as we discussed.
3. agree
4. I would like to use generic logos when possible; maybe we need a data structure that relates generic zim names to logos, like "wikipedia": "<whatever>.png"

the structure of having multiple flavors of zims is greatly simplified in menu-defs

**Comment by georgejhunt** [comment]
1. I'm running into complexity around collision on file names for menu-def stubs coming from rachel and kiwix. I could check for intended_use on any found menu-def, to see whether I should update, or change the new name to be other than "<lang>-<perma_ref>.json. I'm tempted change the algorithm to "<lang>-<perma_ref><intended_use>.json. 
2. Yes, it involves renaming all of our existing menudefs. But it's a one time event, and the program is easy to write, and reduces the collision complexity.
3. I don't want the filenames in /menu-defs folder to depend on the order of downloading rachel and kiwix  content.
4. Maybe you already have a strategy for dealing this this issue. What do you think?

**Comment by georgejhunt** [comment]
But in reality, the frequency of name collision will probably be low. Probably we could let kiwix shadow rachel. I can check for collision, and change the new name to include the intended_use whenever necessary.  The menu.json will still function. As the user downloads content, menu-defs might have a non-deterministic layout. But locally they will still function.

**Comment by tim-moody** [comment]
For now I think that is the right answer. Once no one needs to type a name then adding complexity is not as much of a problem. (we still lose backwards compatibility on existing menus) A check could also be done to see if someone created a menu def for the content in question with a non-canonical name. (phet comes to mind as the only collision so far as there is a rachel module and a zim and the zim does not follow kiwix naming convention. I called it phet_zim.json, which perhaps should be renamed to phet_kiwix.json.)

**Comment by georgejhunt** [comment]
This is complete
