### ISSUE TITLE
Use of Nginx for Admin Console requires Authentication mechanism that works

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab-admin-console#97]

**Comment by georgejhunt** [comment]
Tim's problem statement:
1.The blocker for me to use nginx is Admin Console authentication, which needs apache mod_auth and mod_wsgi. I wish we had another mechanism with a token or something that could be passed directly to command server. I'm sure nodejs must have such a mechanism, but I have not researched it. The idea would be to eliminate the python wrapper and have the front end talk directly to the backend. But I would still like to authenticate off of the linux user name and password so as not to introduce a new user. The crux of the security model for cmdsrv is that it listens on an ipc pipe that has permissions, so we have to make sure that another mechanism is equally secure.

**Comment by georgejhunt** [comment]
moving admin console from apache to nginx is put off to a later releasse

**Comment by tim-moody** [comment]
done
