### ISSUE TITLE
Admin Console download of OpenMapTiles.com requires catalog of URLs [OSM]

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab-admin-console#98]
Tim's problem statement:
4. Add Get OSM Tiles to Admin Console Install Content (without using iframes). What I would like would be to capture the navigation html, especially the region tree, allow a click, and capture the download url, which would then be passed to the cmdsrv to actually do the download and then run your db merge on it.

**Comment by holta** [comment]
Refs:

#877 (Package up vector-based OSM maps)
#1170 (Haiti Diaspora Map Pack)
#1192 (Overcrowding of OSM map labels at Zoom Levels 13 and 14...in cities)

**Comment by georgejhunt** [comment]
put off to a later release

**Comment by tim-moody** [comment]
we have now caught up with this
